name: Harbor
version: 1.5
main: mykyta.Harbor.Harbor
description: Ahoy, matey! Harbor is a Spigot plugin that redefines how sleep works in your server, making it easier for all the online players to get in bed quick and skip through the night!
author: Mykyta (TechToolbox)
website: https://mykyta.tk 

commands:
  harbor:
    description: List information and control Harbor.
    usage: /<command>

