name: ${name}
description: Harbor is a Spigot plugin that redefines how sleep works in your server, making it easier for all the online players to get in bed quickly and skip through the night!
main: xyz.nkomarn.${name}.${name}
version: ${version}
author: TechToolbox (@nkomarn)
website: https://nkomarn.xyz
softdepend: [Essentials]
api-version: 1.13

commands:
  harbor:
    description: "Base command for Harbor!"
    usage: "/harbor {subcommand}"
  sleeping:
    description: "Display a list of the currently sleeping players."
    usage: "/sleeping"